{{- if .Values.gateway.certificates }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hybrid-gateway-conf-{{ include "tyk-hybrid.fullname" . }}
  labels:
    app: gateway-{{ include "tyk-hybrid.fullname" . }}
    chart: {{ include "tyk-hybrid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  tyk_hybrid.conf: |
    {
      "http_server_options": {
        "certificates": [
        {{- range $i, $certset := .Values.gateway.certificates }}
          {
            "cert_file": "/etc/certs/{{ certset.certFilename }}",
            "key_file": "/etc/certs/{{ certset.keyFilename }}"
          }{{- if lt $i (len .Values.gateway.certificates) }},{{- end }}
        {{- end }}
        ]
      }
    }  
{{- end }}
