apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-k8s-conf
  labels:
    app: controller-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  tyk_k8s.yaml: |-
    Server:
      addr: ":443"
      certFile: "/etc/tyk-k8s/certs/cert.pem"
      keyFile: "/etc/tyk-k8s/certs/key.pem"
    Tyk:
      url: "http://dashboard-svc-{{ include "tyk-pro.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.dash.service.port }}"
      secret: "set-by-env"
      org: "set-by-env"
    Injector:
      createRoutes: true
      containers:
        - name: tyk-mesh
          image: tykio/tyk-sidecar:2.7.5
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIGOCLUSTER_SHARDCOUNT
              value: "{{ .Values.redis.shardCount }}"
            - name: TYK_GW_STORAGE_HOSTS
              value: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
            - name: TYK_GW_STORAGE_USESSL
              value: "false"
            - name: TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING
              value: "http://dashboard-svc-{{ include "tyk-pro.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.dash.service.port }}"
            - name: TYK_GW_POLICIES_POLICYCONNECTIONSTRING
              value: "http://dashboard-svc-{{ include "tyk-pro.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.dash.service.port }}"
            - name: TYK_GW_SECRET
              value: "{{ .Values.secrets.APISecret }}"
            - name: TYK_GW_NODESECRET
              value: "{{ .Values.secrets.APISecret }}"
            - name: TYK_GW_ENABLECUSTOMDOMAINS
              value: "true"
          command: ["/opt/tyk-gateway/tyk", "--conf=/opt/tyk-gateway/tyk.conf"]
          workingDir: /opt/tyk-gateway
          ports:
            - containerPort: 8080
      initContainers:
        - image: tykio/tyk-k8s-init
          imagePullPolicy: Always
          name: run-iptables
          securityContext:
            privileged: true
          command:
            - "/entrypoint"
